### ISSUE TITLE
Rename KlaytnScope to KaiaScope 

### ISSUE THREAD

**Issue by ayo-klaytn** [kaiachain/awesome-kaia#5]
Kindly rename KlaytnScope to KaiaScope under `Chain Data Explorers` section. URL remains the same.

**Comment by snehasharma76** [comment]
Raised a PR https://github.com/snehasharma76/awesome-kaia/pull/1

**Comment by ayo-klaytn** [comment]
This issue has been fixed. Thanks to @snehasharma76 🎉
<img width="892" alt="Screenshot 2024-08-07 at 09 26 12" src="https://github.com/user-attachments/assets/0beda9c2-fb0c-4c4a-9406-18b610e082ab">
